---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      initContainers:
        - name: init-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_HOST
              value: "mysql-0.mysql.default.svc.cluster.local"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "messages_db"
          command:
            - "/bin/sh"
            - "-c"
            - |
              until mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e "SELECT 1"; do
                echo 'Waiting for MySQL...';
                sleep 5;
              done;
              echo 'MySQL is up. Creating table if not exists...';
              mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e "
              CREATE DATABASE messages_db;
              USE messages_db;
              CREATE TABLE IF NOT EXISTS messages (
                id INT AUTO_INCREMENT PRIMARY KEY,
                event VARCHAR(255) NOT NULL,
                user_id VARCHAR(255) NOT NULL,
                timestamp DATETIME NOT NULL
              );
              ";
      containers:
        - name: consumer
          image: docker.io/muk007/consumer:12
          env:
            - name: SQS_QUEUE_URL
              value: "https://sqs.us-west-2.amazonaws.com/014337110715/kind-cluster-sqs-queue"
