---
apiVersion: batch/v1
kind: Job
metadata:
  name: publisher-job
spec:
  template:
    metadata:
      labels:
        app: publisher
    spec:
      restartPolicy: Never
      containers:
        - name: publisher
          image: docker.io/muk007/publisher:9
          env:
            - name: SQS_QUEUE_URL
              value: "https://sqs.us-west-2.amazonaws.com/014337110715/kind-cluster-sqs-queue"