---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          image: docker.io/muk007/publisher
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: publisher-service
  labels:
    app: publisher
spec:
  selector:
    app: publisher
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP