name: Build and Deploy

on:
  workflow_dispatch:
  
  push:
    branches: ["main"]
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.TAG }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Tag Number
        id: set_tag
        run: |
          VERSION="${{ github.run_number }}"
          echo "TAG=$VERSION" >> $GITHUB_ENV
          echo "TAG=$VERSION" >> $GITHUB_OUTPUT  # Save output

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image with Context (publisher)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: devops/publisher.Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/publisher:${{ env.TAG }}"

      - name: Build Docker Image with Context (consumer)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: devops/consumer.Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/consumer:${{ env.TAG }}"

    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Transform version for TAG
        run: echo "TAG=$(echo '${{ needs.build.outputs.image_tag }}')" >> $GITHUB_ENV
          
      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Update Version in File
        run: |
          export CONSUMER_IMAGE_TAG="docker.io/muk007/consumer:${TAG}"
          export PUBLISHER_IMAGE_TAG="docker.io/muk007/publisher:${TAG}"
          yq -i ".spec.template.spec.containers[0].image = \"${CONSUMER_IMAGE_TAG}\"" manifests/consumer.yaml
          yq -i ".spec.template.spec.containers[0].image = \"${PUBLISHER_IMAGE_TAG}\"" manifests/publisher.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          branch: "update-tag-br"
          base: "main"
          title: "Update image tag"
          body: "Update image tag for reader and writer"
          labels: automated