name: Create Infra

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  apply-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      #- name: Configure AWS creds
      #  uses: aws-actions/configure-aws-credentials@v4
      #  with:
      #    role-to-assume: arn:aws:iam::014337110715:role/github-actions-role
      #    aws-region: us-west-2
   
      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Apply changes
        run: |
          terraform -chdir=terraform init
          terraform -chdir=terraform validate
          terraform -chdir=terraform plan
          terraform -chdir=terraform apply -auto-approve

      - name: Wait (Until startup script finishes)
        run: sleep 300

      - name: Apply Manifests
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=kind-cluster" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text)
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=$INSTANCE_ID" \
            --parameters '{
              "commands": [
                "export KUBECONFIG=/home/ubuntu/.kube/config",
                "cd /home/ubuntu",
                "rm -rf KEDA-implementation", 
                "git clone https://github.com/devops-contribution/KEDA-implementation.git",
                "kubectl apply -f ./KEDA-implementation/manifests/.",
                "kubectl create secret generic aws-sqs-credentials \
                 --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                 --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
              ]
            }' \
            --comment "Apply Kubernetes manifests"
